{{- define "daemonset-volumes-linux" -}}
- hostPath:
    path: /proc
  name: procdir
- hostPath:
    path: /sys/fs/cgroup
  name: cgroups
{{- if .Values.datadog.dogstatsd.useSocketVolume }}
- hostPath:
    path: {{ .Values.datadog.dogstatsd.hostSocketPath }}
    type: DirectoryOrCreate
  name: dsdsocket
{{- end }}
{{- if .Values.datadog.apm.useSocketVolume }}
- hostPath:
    path: {{ .Values.datadog.apm.hostSocketPath }}
    type: DirectoryOrCreate
  name: apmsocket
{{- end }}
- name: s6-run
  emptyDir: {}
{{- if (or (.Values.datadog.confd) (.Values.datadog.autoconf)) }}
- name: confd
  configMap:
    name: {{ template "datadog.fullname" . }}-confd
{{- end }}
{{- if or .Values.datadog.systemProbe.enabled .Values.datadog.securityAgent.runtime.enabled}}
- name: sysprobe-config
  configMap:
    name: {{ template "datadog.fullname" . }}-system-probe-config
{{- if eq .Values.datadog.systemProbe.seccomp "localhost/system-probe" }}
- name: datadog-agent-security
  configMap:
    name: {{ template "datadog.fullname" . }}-security
- hostPath:
    path: {{ .Values.datadog.systemProbe.seccompRoot }}
  name: seccomp-root
{{- end }}
- hostPath:
    path: /sys/kernel/debug
  name: debugfs
- name: sysprobe-socket-dir
  emptyDir: {}
{{- if or .Values.datadog.systemProbe.enableTCPQueueLength .Values.datadog.systemProbe.enableOOMKill }}
- hostPath:
    path: /lib/modules
  name: modules
- hostPath:
    path: /usr/src
  name: src
{{- end }}
{{- end }}
{{- if .Values.datadog.systemProbe.enabled }}
- hostPath:
    path: /etc/apt
    type: DirectoryOrCreate
  name: etc-apt
- hostPath:
    path: /etc/yum
    type: DirectoryOrCreate
  name: etc-yum
- hostPath:
    path: /etc/yum.repos.d
    type: DirectoryOrCreate
  name: yum-sources
- hostPath:
    path: /etc/debian_version
    type: FileOrCreate
  name: debian-version
- hostPath:
    path: /etc/system-release-cpe
    type: FileOrCreate
  name: system-release
{{- end }}
{{- if or .Values.datadog.processAgent.enabled .Values.datadog.systemProbe.enabled .Values.datadog.securityAgent.compliance.enabled .Values.datadog.securityAgent.runtime.enabled }}
- hostPath:
    path: /etc/passwd
  name: passwd
{{- end }}
{{- if .Values.datadog.securityAgent.compliance.enabled }}
- hostPath:
    path: /etc/group
  name: group
- hostPath:
    path: /
  name: hostroot
{{- if .Values.datadog.securityAgent.compliance.configMap }}
- name: complianceconfigdir
  configMap:
    name: {{ .Values.datadog.securityAgent.compliance.configMap }}
{{- end }}
{{- end }}
{{- if and .Values.datadog.securityAgent.runtime.enabled .Values.datadog.securityAgent.runtime.policies.configMap }}
- name: runtimepoliciesdir
  configMap:
    name: {{ .Values.datadog.securityAgent.runtime.policies.configMap }}
{{- end }}
{{- if or .Values.datadog.logs.enabled .Values.datadog.logsEnabled }}
- hostPath:
    path: "/var/lib/datadog-agent/logs"
  name: pointerdir
- hostPath:
    path: /var/log/pods
  name: logpodpath
{{- if not .Values.datadog.criSocketPath }}
- hostPath:
    path: /var/lib/docker/containers
  name: logdockercontainerpath
{{- end }}
{{- end }}
{{- end -}}
